{
  "hash": "f027e8fb6793868d75523fb77fca206d",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Non-linear Modeling\"\nformat: html\neditor: visual\n---\n\n::: {.cell}\n\n:::\n\n\n# \n\nIn this lab, we re-analyze the `Wage` data considered in the examples throughout this chapter, in order to illustrate the fact that many of the complex non-linear fitting procedures discussed can be easily implemented in `R`. We begin by loading the `ISLR2` library, which contains the data.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(ISLR2)\nattach(Wage)\n```\n:::\n\n\n## Polynomial Regression and Step Functions\n\nWe now examine how Figure 7.1 was produced. We first fit the model using the following command:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfit <- lm(wage ~ poly(age, 4), data = Wage)\ncoef(summary(fit))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                Estimate Std. Error    t value     Pr(>|t|)\n(Intercept)    111.70361  0.7287409 153.283015 0.000000e+00\npoly(age, 4)1  447.06785 39.9147851  11.200558 1.484604e-28\npoly(age, 4)2 -478.31581 39.9147851 -11.983424 2.355831e-32\npoly(age, 4)3  125.52169 39.9147851   3.144742 1.678622e-03\npoly(age, 4)4  -77.91118 39.9147851  -1.951938 5.103865e-02\n```\n\n\n:::\n:::\n\n\nThis syntax fits a linear model, using the `lm()` function, in order to predict `wage` using a fourth-degree polynomial in `age`: `poly(age, 4)`. The `poly()` command allows us to avoid having to write out a long formula with powers of `age`. The function returns a matrix whose columns are a basis of *orthogonal polynomials*, which essentially means that each column is a linear combination of the variables `age`, `age^2`, `age^3` and `age^4`.\n\nHowever, we can also use `poly()` to obtain `age`, `age^2`, `age^3` and `age^4` directly, if we prefer. We can do this by using the `raw = TRUE` argument to the `poly()` function. Later we see that this does not affect the model in a meaningful way---though the choice of basis clearly affects the coefficient estimates, it does not affect the fitted values obtained.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfit2 <- lm(wage ~ poly(age, 4, raw = T), data = Wage)\ncoef(summary(fit2))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                            Estimate   Std. Error   t value     Pr(>|t|)\n(Intercept)            -1.841542e+02 6.004038e+01 -3.067172 0.0021802539\npoly(age, 4, raw = T)1  2.124552e+01 5.886748e+00  3.609042 0.0003123618\npoly(age, 4, raw = T)2 -5.638593e-01 2.061083e-01 -2.735743 0.0062606446\npoly(age, 4, raw = T)3  6.810688e-03 3.065931e-03  2.221409 0.0263977518\npoly(age, 4, raw = T)4 -3.203830e-05 1.641359e-05 -1.951938 0.0510386498\n```\n\n\n:::\n:::\n\n\nThere are several other equivalent ways of fitting this model, which showcase the flexibility of the formula language in `R`. For example\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfit2a <- lm(wage ~ age + I(age^2) + I(age^3) + I(age^4),\n    data = Wage)\ncoef(fit2a)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  (Intercept)           age      I(age^2)      I(age^3)      I(age^4) \n-1.841542e+02  2.124552e+01 -5.638593e-01  6.810688e-03 -3.203830e-05 \n```\n\n\n:::\n:::\n\n\nThis simply creates the polynomial basis functions on the fly, taking care to protect terms like `age^2` via the *wrapper* function `I()` (the `^` symbol has a special meaning in formulas).\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfit2b <- lm(wage ~ cbind(age, age^2, age^3, age^4),\n    data = Wage)\n```\n:::\n\n\nThis does the same more compactly, using the `cbind()` function for building a matrix from a collection of vectors; any function call such as `cbind()` inside a formula also serves as a wrapper.\n\nWe now create a grid of values for `age` at which we want predictions, and then call the generic `predict()` function, specifying that we want standard errors as well.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nagelims <- range(age)\nage.grid <- seq(from = agelims[1], to = agelims[2])\npreds <- predict(fit, newdata = list(age = age.grid),\n    se = TRUE)\nse.bands <- cbind(preds$fit + 2 * preds$se.fit,\n    preds$fit - 2 * preds$se.fit)\n```\n:::\n\n\nFinally, we plot the data and add the fit from the degree-4 polynomial.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npar(mfrow = c(1, 2), mar = c(4.5, 4.5, 1, 1),oma = c(0, 0, 4, 0))\nplot(age, wage, xlim = agelims, cex = .5, col = \"darkgrey\")\ntitle(\"Degree-4 Polynomial\", outer = T)\nlines(age.grid, preds$fit, lwd = 2, col = \"blue\")\nmatlines(age.grid, se.bands, lwd = 1, col = \"blue\", lty = 3)\n```\n\n::: {.cell-output-display}\n![](08_nonlinear_modeling_files/figure-html/chunk7-1.png){width=672}\n:::\n:::\n\n\nHere the `mar` and `oma` arguments to `par()` allow us to control the margins of the plot, and the `title()` function creates a figure title that spans both subplots.\n\nWe mentioned earlier that whether or not an orthogonal set of basis functions is produced in the `poly()` function will not affect the model obtained in a meaningful way. What do we mean by this? The fitted values obtained in either case are identical:\n\n\n::: {.cell}\n\n```{.r .cell-code}\npreds2 <- predict(fit2, newdata = list(age = age.grid),\n    se = TRUE)\nmax(abs(preds$fit - preds2$fit))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 6.88658e-11\n```\n\n\n:::\n:::\n\n\nIn performing a polynomial regression we must decide on the degree of the polynomial to use. One way to do this is by using hypothesis tests. We now fit models ranging from linear to a degree-5 polynomial and seek to determine the simplest model which is sufficient to explain the relationship between `wage` and `age`. We use the `anova()` function, which performs an *analysis of variance* (ANOVA, using an F-test) in order to test the null hypothesis that a model $M_1$ is sufficient to explain the data against the alternative hypothesis that a more complex model $M_2$ is required. In order to use the `anova()` function, $M_1$ and $M_2$ must be *nested* models: the predictors in $M_1$ must be a subset of the predictors in $M_2$. In this case, we fit five different models and sequentially compare the simpler model to the more complex model.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfit.1 <- lm(wage ~ age, data = Wage)\nfit.2 <- lm(wage ~ poly(age, 2), data = Wage)\nfit.3 <- lm(wage ~ poly(age, 3), data = Wage)\nfit.4 <- lm(wage ~ poly(age, 4), data = Wage)\nfit.5 <- lm(wage ~ poly(age, 5), data = Wage)\nanova(fit.1, fit.2, fit.3, fit.4, fit.5)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnalysis of Variance Table\n\nModel 1: wage ~ age\nModel 2: wage ~ poly(age, 2)\nModel 3: wage ~ poly(age, 3)\nModel 4: wage ~ poly(age, 4)\nModel 5: wage ~ poly(age, 5)\n  Res.Df     RSS Df Sum of Sq        F    Pr(>F)    \n1   2998 5022216                                    \n2   2997 4793430  1    228786 143.5931 < 2.2e-16 ***\n3   2996 4777674  1     15756   9.8888  0.001679 ** \n4   2995 4771604  1      6070   3.8098  0.051046 .  \n5   2994 4770322  1      1283   0.8050  0.369682    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\nThe p-value comparing the linear `Model 1` to the quadratic `Model 2` is essentially zero ($<$$10^{-15}$), indicating that a linear fit is not sufficient. Similarly the p-value comparing the quadratic `Model 2` to the cubic `Model 3` is very low ($0.0017$), so the quadratic fit is also insufficient. The p-value comparing the cubic and degree-4 polynomials, `Model 3` and `Model 4`, is approximately $5 \\%$ while the degree-5 polynomial `Model 5` seems unnecessary because its p-value is $0.37$. Hence, either a cubic or a quartic polynomial appear to provide a reasonable fit to the data, but lower- or higher-order models are not justified.\n\nIn this case, instead of using the `anova()` function, we could have obtained these p-values more succinctly by exploiting the fact that `poly()` creates orthogonal polynomials.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncoef(summary(fit.5))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                Estimate Std. Error     t value     Pr(>|t|)\n(Intercept)    111.70361  0.7287647 153.2780243 0.000000e+00\npoly(age, 5)1  447.06785 39.9160847  11.2001930 1.491111e-28\npoly(age, 5)2 -478.31581 39.9160847 -11.9830341 2.367734e-32\npoly(age, 5)3  125.52169 39.9160847   3.1446392 1.679213e-03\npoly(age, 5)4  -77.91118 39.9160847  -1.9518743 5.104623e-02\npoly(age, 5)5  -35.81289 39.9160847  -0.8972045 3.696820e-01\n```\n\n\n:::\n:::\n\n\nNotice that the p-values are the same, and in fact the square of the $t$-statistics are equivalent to the F-statistics from the `anova()` function; for example:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n(-11.983)^2\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 143.5923\n```\n\n\n:::\n:::\n\n\nHowever, the ANOVA method works whether or not we used orthogonal polynomials; it also works when we have other terms in the model as well. For example, we can use `anova()` to compare these three models:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfit.1 <- lm(wage ~ education + age, data = Wage)\nfit.2 <- lm(wage ~ education + poly(age, 2), data = Wage)\nfit.3 <- lm(wage ~ education + poly(age, 3), data = Wage)\nanova(fit.1, fit.2, fit.3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnalysis of Variance Table\n\nModel 1: wage ~ education + age\nModel 2: wage ~ education + poly(age, 2)\nModel 3: wage ~ education + poly(age, 3)\n  Res.Df     RSS Df Sum of Sq        F Pr(>F)    \n1   2994 3867992                                 \n2   2993 3725395  1    142597 114.6969 <2e-16 ***\n3   2992 3719809  1      5587   4.4936 0.0341 *  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\nAs an alternative to using hypothesis tests and ANOVA, we could choose the polynomial degree using cross-validation, as discussed in Chapter 5.\n\nNext we consider the task of predicting whether an individual earns more than $250{,}000$ per year. We proceed much as before, except that first we create the appropriate response vector, and then apply the `glm()` function using `family = \"binomial\"` in order to fit a polynomial logistic regression model.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfit <- glm(I(wage > 250) ~ poly(age, 4), data = Wage,\n    family = binomial)\n```\n:::\n\n\nNote that we again use the wrapper `I()` to create this binary response variable on the fly. The expression `wage > 250` evaluates to a logical variable containing `TRUE`s and `FALSE`s, which `glm()` coerces to binary by setting the `TRUE`s to 1 and the `FALSE`s to 0.\n\nOnce again, we make predictions using the `predict()` function.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npreds <- predict(fit, newdata = list(age = age.grid), se = T)\n```\n:::\n\n\nHowever, calculating the confidence intervals is slightly more involved than in the linear regression case. The default prediction type for a `glm()` model is `type = \"link\"`, which is what we use here. This means we get predictions for the *logit*, or log-odds: that is, we have fit a model of the form\n\n$$\n\\log\\left(\\frac{\\Pr(Y=1|X)}{1-\\Pr(Y=1|X)}\\right) = X\\beta\n$$ and the predictions given are of the form $X\\hat\\beta$. The standard errors given are also for $X \\hat\\beta$. In order to obtain confidence intervals for $\\Pr(Y=1|X)$, we use the transformation $$\n\\Pr(Y=1\\|X)=\\frac{\\exp(X\\beta)}{1+\\exp(X\\beta)}\n$$\n\n\n::: {.cell}\n\n```{.r .cell-code}\npfit <- exp(preds$fit) / (1 + exp(preds$fit))\nse.bands.logit <- cbind(preds$fit + 2 * preds$se.fit,\n    preds$fit - 2 * preds$se.fit)\nse.bands <- exp(se.bands.logit) / (1 + exp(se.bands.logit))\n```\n:::\n\n\nNote that we could have directly computed the probabilities by selecting the `type = \"response\"` option in the `predict()` function.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npreds <- predict(fit, newdata = list(age = age.grid), type = \"response\", se = T)\n```\n:::\n\n\nHowever, the corresponding confidence intervals would not have been sensible because we would end up with negative probabilities!\n\nFinally, the right-hand plot from Figure 7.1 was made as follows:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(age, I(wage > 250), xlim = agelims, type = \"n\",\n    ylim = c(0, .2))\npoints(jitter(age), I((wage > 250) / 5), cex = .5, pch = \"|\", col = \"darkgrey\")\nlines(age.grid, pfit, lwd = 2, col = \"blue\")\nmatlines(age.grid, se.bands, lwd = 1, col = \"blue\", lty = 3)\n```\n\n::: {.cell-output-display}\n![](08_nonlinear_modeling_files/figure-html/chunk17-1.png){width=672}\n:::\n:::\n\n\nWe have drawn the `age` values corresponding to the observations with `wage` values above $250$ as gray marks on the top of the plot, and those with `wage` values below $250$ are shown as gray marks on the bottom of the plot. We used the `jitter()` function to jitter the `age` values a bit so that observations with the same `age` value do not cover each other up. This is often called a *rug plot*.\n\n## Stepwise\n\nIn order to fit a step function, as discussed in Section 7.2, we use the `cut()` function.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntable(cut(age, 4))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n(17.9,33.5]   (33.5,49]   (49,64.5] (64.5,80.1] \n        750        1399         779          72 \n```\n\n\n:::\n\n```{.r .cell-code}\nfit <- lm(wage ~ cut(age, 4), data = Wage)\ncoef(summary(fit))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                        Estimate Std. Error   t value     Pr(>|t|)\n(Intercept)            94.158392   1.476069 63.789970 0.000000e+00\ncut(age, 4)(33.5,49]   24.053491   1.829431 13.148074 1.982315e-38\ncut(age, 4)(49,64.5]   23.664559   2.067958 11.443444 1.040750e-29\ncut(age, 4)(64.5,80.1]  7.640592   4.987424  1.531972 1.256350e-01\n```\n\n\n:::\n:::\n\n\nHere `cut()` automatically picked the cutpoints at $33.5$, $49$, and $64.5$ years of age. We could also have specified our own cutpoints directly using the `breaks` option. The function `cut()` returns an ordered categorical variable; the `lm()` function then creates a set of dummy variables for use in the regression. The `age < 33.5` category is left out, so the intercept coefficient of \\$$94{,}160$ can be interpreted as the average salary for those under $33.5$ years of age, and the other coefficients can be interpreted as the average additional salary for those in the other age groups. We can produce predictions and plots just as we did in the case of the polynomial fit.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(ggplot2)\nWage$stepwise_fit <- predict(fit)\n\nggplot(Wage, aes(x = age, y = wage)) +\n  geom_point(alpha = 0.5, color = \"blue\") +  \n  geom_step(aes(y = stepwise_fit), color = \"orange\", linewidth = 1) + \n  labs(\n    title = \"Scatterplot with Stepwise Regression Line\",\n    x = \"Age\",\n    y = \"Wage\"\n  ) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](08_nonlinear_modeling_files/figure-html/unnamed-chunk-1-1.png){width=672}\n:::\n:::\n\n\n## Splines\n\nIn order to fit regression splines in `R`, we use the `splines` library. In Section 7.4, we saw that regression splines can be fit by constructing an appropriate matrix of basis functions. The `bs()` function generates the entire matrix of basis functions for splines with the specified set of knots. By default, cubic splines are produced. Fitting `wage` to `age` using a regression spline is simple:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(splines)\nfit <- lm(wage ~ bs(age, knots = c(25, 40, 60)), data = Wage)\npred <- predict(fit, newdata = list(age = age.grid), se = T)\nplot(age, wage, col = \"gray\")\nlines(age.grid, pred$fit, lwd = 2)\nlines(age.grid, pred$fit + 2 * pred$se, lty = \"dashed\")\nlines(age.grid, pred$fit - 2 * pred$se, lty = \"dashed\")\n```\n\n::: {.cell-output-display}\n![](08_nonlinear_modeling_files/figure-html/chunk19-1.png){width=672}\n:::\n:::\n\n\nHere we have prespecified knots at ages $25$, $40$, and $60$. This produces a spline with six basis functions. (Recall that a cubic spline with three knots has seven degrees of freedom; these degrees of freedom are used up by an intercept, plus six basis functions.) We could also use the `df` option to produce a spline with knots at uniform quantiles of the data.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndim(bs(age, knots = c(25, 40, 60)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 3000    6\n```\n\n\n:::\n\n```{.r .cell-code}\ndim(bs(age, df = 6))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 3000    6\n```\n\n\n:::\n\n```{.r .cell-code}\nattr(bs(age, df = 6), \"knots\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 33.75 42.00 51.00\n```\n\n\n:::\n:::\n\n\nIn this case `R` chooses knots at ages $33.8, 42.0$, and $51.0$, which correspond to the 25th, 50th, and 75th percentiles of `age`. The function `bs()` also has a `degree` argument, so we can fit splines of any degree, rather than the default degree of 3 (which yields a cubic spline).\n\nIn order to instead fit a natural spline, we use the `ns()` function. Here we fit a natural spline with four degrees of freedom.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfit2 <- lm(wage ~ ns(age, df = 4), data = Wage)\npred2 <- predict(fit2, newdata = list(age = age.grid),\n     se = T)\nplot(age, wage, col = \"gray\")\nlines(age.grid, pred2$fit, col = \"red\", lwd = 2)\nlines(age.grid, pred2$fit + 2 * pred2$se, lty = \"dashed\")\nlines(age.grid, pred2$fit - 2 * pred2$se, lty = \"dashed\")\n```\n\n::: {.cell-output-display}\n![](08_nonlinear_modeling_files/figure-html/chunk21-1.png){width=672}\n:::\n:::\n\n\nAs with the `bs()` function, we could instead specify the knots directly using the `knots` option.\n\nIn order to fit a smoothing spline, we use the `smooth.spline()` function. Figure 7.8 was produced with the following code:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(age, wage, xlim = agelims, cex = .5, col = \"darkgrey\", ylim = c(0,200))\ntitle(\"Smoothing Spline\")\nfit <- smooth.spline(age, wage, df = 3)\nfit2 <- smooth.spline(age, wage, df = 16)\nfit3 <- smooth.spline(age, wage, cv = TRUE)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in smooth.spline(age, wage, cv = TRUE): cross-validation with\nnon-unique 'x' values seems doubtful\n```\n\n\n:::\n\n```{.r .cell-code}\nfit3$df\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 6.794596\n```\n\n\n:::\n\n```{.r .cell-code}\nlines(fit, col = \"red\", lwd = 2.5)\nlines(fit2, col = \"blue\", lwd = 2.5)\nlines(fit3, col = \"green\", lwd = 2.5)\nlegend(\"topright\",\n       legend = c(\"3 DF\", \"16 DF\", \"6.8 DF\"),\n       col = c(\"red\", \"blue\", \"green\"),\n       lty = 1, lwd = 2, cex = .8)\n```\n\n::: {.cell-output-display}\n![](08_nonlinear_modeling_files/figure-html/chunk22-1.png){width=672}\n:::\n:::\n\n\nNotice that in the first call to `smooth.spline()`, we specified `df = 16`. The function then determines which value of $\\lambda$ leads to $16$ degrees of freedom. In the second call to `smooth.spline()`, we select the smoothness level by cross-validation; this results in a value of $\\lambda$ that yields 6.8 degrees of freedom.\n\n## GAMs\n\nWe now fit a GAM to predict `wage` using natural spline functions of `lyear` and `age`, treating `education` as a qualitative predictor, as in (7.16). Since this is just a big linear regression model using an appropriate choice of basis functions, we can simply do this using the `lm()` function.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngam1 <- lm(wage ~ ns(year, 4) + ns(age, 5) + education, data = Wage)\n```\n:::\n\n\nWe now fit the model (7.16) using smoothing splines rather than natural splines. In order to fit more general sorts of GAMs, using smoothing splines or other components that cannot be expressed in terms of basis functions and then fit using least squares regression, we will need to use the `gam` library in `R`.\n\nThe `s()` function, which is part of the `gam` library, is used to indicate that we would like to use a smoothing spline. We specify that the function of `lyear` should have $4$ degrees of freedom, and that the function of `age` will have $5$ degrees of freedom. Since `education` is qualitative, we leave it as is, and it is converted into four dummy variables. We use the `gam()` function in order to fit a GAM using these components. All of the terms in (7.16) are fit simultaneously, taking each other into account to explain the response.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(gam)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nLoading required package: foreach\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nLoaded gam 1.22-5\n```\n\n\n:::\n\n```{.r .cell-code}\ngam.m3 <- gam(wage ~ s(year, 4) + s(age, 5) + education,\n    data = Wage)\n```\n:::\n\n\nIn order to produce Figure 7.12, we simply call the `plot()` function:\n\n\n::: {.cell}\n\n```{.r .cell-code}\npar(mfrow = c(1, 3))\nplot(gam.m3, se = TRUE, col = \"blue\")\n```\n\n::: {.cell-output-display}\n![](08_nonlinear_modeling_files/figure-html/chunk26-1.png){width=672}\n:::\n:::\n\n\nThe generic `plot()` function recognizes that `gam.m3` is an object of class `Gam`, and invokes the appropriate `plot.Gam()` method. Conveniently, even though `gam1` is not of class `Gam` but rather of class `lm`, we can {\\em\n  still} use `plot.Gam()` on it. Figure 7.11 was produced using the following expression:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot.Gam(gam1, se = TRUE, col = \"red\")\n```\n\n::: {.cell-output-display}\n![](08_nonlinear_modeling_files/figure-html/chunk27-1.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](08_nonlinear_modeling_files/figure-html/chunk27-2.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](08_nonlinear_modeling_files/figure-html/chunk27-3.png){width=672}\n:::\n:::\n\n\nNotice here we had to use `plot.Gam()` rather than the *generic* `plot()` function.\n\nIn these plots, the function of `lyear` looks rather linear. We can perform a series of ANOVA tests in order to determine which of these three models is best: a GAM that excludes `lyear` ($M_1$), a GAM that uses a linear function of `lyear` ($M_2$), or a GAM that uses a spline function of `lyear` ($M_3$).\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngam.m1 <- gam(wage ~ s(age, 5) + education, data = Wage)\ngam.m2 <- gam(wage ~ year + s(age, 5) + education,\n    data = Wage)\nanova(gam.m1, gam.m2, gam.m3, test = \"F\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnalysis of Deviance Table\n\nModel 1: wage ~ s(age, 5) + education\nModel 2: wage ~ year + s(age, 5) + education\nModel 3: wage ~ s(year, 4) + s(age, 5) + education\n  Resid. Df Resid. Dev Df Deviance       F    Pr(>F)    \n1      2990    3711731                                  \n2      2989    3693842  1  17889.2 14.4771 0.0001447 ***\n3      2986    3689770  3   4071.1  1.0982 0.3485661    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\nWe find that there is compelling evidence that a GAM with a linear function of `lyear` is better than a GAM that does not include `lyear` at all (p-value = 0.00014). However, there is no evidence that a non-linear function of `lyear` is needed (p-value = 0.349). In other words, based on the results of this ANOVA, $M_2$ is preferred.\n\nThe `summary()` function produces a summary of the gam fit.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(gam.m3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall: gam(formula = wage ~ s(year, 4) + s(age, 5) + education, data = Wage)\nDeviance Residuals:\n    Min      1Q  Median      3Q     Max \n-119.43  -19.70   -3.33   14.17  213.48 \n\n(Dispersion Parameter for gaussian family taken to be 1235.69)\n\n    Null Deviance: 5222086 on 2999 degrees of freedom\nResidual Deviance: 3689770 on 2986 degrees of freedom\nAIC: 29887.75 \n\nNumber of Local Scoring Iterations: NA \n\nAnova for Parametric Effects\n             Df  Sum Sq Mean Sq F value    Pr(>F)    \ns(year, 4)    1   27162   27162  21.981 2.877e-06 ***\ns(age, 5)     1  195338  195338 158.081 < 2.2e-16 ***\neducation     4 1069726  267432 216.423 < 2.2e-16 ***\nResiduals  2986 3689770    1236                      \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nAnova for Nonparametric Effects\n            Npar Df Npar F  Pr(F)    \n(Intercept)                          \ns(year, 4)        3  1.086 0.3537    \ns(age, 5)         4 32.380 <2e-16 ***\neducation                            \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\nThe \"Anova for Parametric Effects\" p-values clearly demonstrate that `year`, `age`, and `education` are all highly statistically significant, even when only assuming a linear relationship. Alternatively, the \"Anova for Nonparametric Effects\" p-values for `year` and `age` correspond to a null hypothesis of a linear relationship versus the alternative of a non-linear relationship. The large p-value for `year` reinforces our conclusion from the ANOVA test that a linear function is adequate for this term. However, there is very clear evidence that a non-linear term is required for `age`.\n\nWe can make predictions using the `predict()` method for the class `Gam`. Here we make predictions on the training set.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npreds <- predict(gam.m2, newdata = Wage)\n```\n:::\n\n\nIn order to fit a logistic regression GAM, we once again use the `I()` function in constructing the binary response variable, and set `family=binomial`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngam.lr <- gam(\n    I(wage > 250) ~ year + s(age, df = 5) + education,\n    family = binomial, data = Wage\n  )\npar(mfrow = c(1, 3))\nplot(gam.lr, se = T, col = \"green\")\n```\n\n::: {.cell-output-display}\n![](08_nonlinear_modeling_files/figure-html/chunk34-1.png){width=672}\n:::\n:::\n\n\nIt is easy to see that there are no high earners in the `< HS` category:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntable(education, I(wage > 250))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                    \neducation            FALSE TRUE\n  1. < HS Grad         268    0\n  2. HS Grad           966    5\n  3. Some College      643    7\n  4. College Grad      663   22\n  5. Advanced Degree   381   45\n```\n\n\n:::\n:::\n\n\nHence, we fit a logistic regression GAM using all but this category. This provides more sensible results.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngam.lr.s <- gam(\n    I(wage > 250) ~ year + s(age, df = 5) + education,\n    family = binomial, data = Wage,\n    subset = (education != \"1. < HS Grad\")\n  )\nplot(gam.lr.s, se = T, col = \"green\")\n```\n\n::: {.cell-output-display}\n![](08_nonlinear_modeling_files/figure-html/chunk36-1.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](08_nonlinear_modeling_files/figure-html/chunk36-2.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](08_nonlinear_modeling_files/figure-html/chunk36-3.png){width=672}\n:::\n:::\n",
    "supporting": [
      "08_nonlinear_modeling_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}