---
title: Data Science with Tidyverse I
subtitle: Data Wrangling & Visualization
description: |
  The **Tidyverse** is a collection of packages in the statistical software R that provides a consistent and efficient framework for data manipulation, exploration, and visualization. It emphasizes using tidy data principles and functional programming techniques to simplify and streamline data analysis workflows. This course provides structured guidance on how to use tidyverse tools to simplify data importing, cleaning, processing and visualization. This is illustrated using realistic worked examples throughout the course.
section-divs: false
toc: false
margin-footer: licence.html
---


:::{.highlight}
*Make sure to install and load Tidyverse:*
```{r}
#| eval: false
install.packages("tidyverse")
library(tidyverse)
```
:::


## Schedule

|                                                    | slides  | practical | data | worksheet | 
|----------------------------------------------------|:------:|:---------:|:---------:|:---------:|
| **1**: Meet the toolkit | [{{< fa display >}}](https://termehs.github.io/tidy01-meet-the-toolkit)  |  [{{< fa file >}}](material/bechdel.qmd)  |  | [.qmd](material/bechdel-ws.zip)  |
| **2**:  Data visualization and ggplot  |  [{{< fa display >}}](https://termehs.github.io/tidy02-data-viz-ggplot)  |  [{{< fa file >}}](material/starwars.qmd)   |  |[.qmd](material/starwars-ws.zip)
| **3**:  Visualizing numerical and categorical data |  [{{< fa display >}}](https://termehs.github.io/tidy03-data-viz-num-cat)  |  [{{< fa file >}}](material/plastic-waste.qmd)   |  [.zip](material/data-pw.zip)|   [.qmd](material/plastic-waste-ws.zip) |
| **4**: Effective Visualization |  [{{< fa display >}}](https://termehs.github.io/tidy04-effective-dataviz)  |  [{{< fa file >}}](material/brexit.qmd)    |  [.zip](material/data-brexit.zip)|  [.qmd](material/brexit-ws.zip) |
| **5**:  Grammar of data wrangling I|  [{{< fa display >}}](https://termehs.github.io/tidy05-grammar-wrangle-single-df)  |  [{{< fa file >}}](material/hotels-datawrangling.qmd)   [{{< fa file >}}](material/nobel-laureates.qmd)   |  [.zip](material/data-4-wrangling-I.zip)| [.qmd](material/datawrangling-I-ws.zip)  |
| **6**:  Grammar of data wrangling II| [{{< fa display >}}](https://termehs.github.io/tidy06-grammar-wrangle-multiple-df)  | [{{< fa file >}}](material/la-quinta.qmd) |  [.zip](material/data-4-wrangling-II.zip)| [.qmd](material/la-quinta-ws.zip)  |
| **7**:  Tidying Data|  [{{< fa display >}}](https://termehs.github.io/tidy07-tidying)  | |  [.zip](material/data-tidying.zip)| |
|  \ \ \ \  *More Practicals*| | [{{< fa file >}}](material/college-majors.qmd)   [{{< fa file >}}](material/legos.qmd)   | [.zip](material//data_extra_practicals.zip) | [.qmd](material/extra-practical-ws.zip)|  
| **8**:  Data Types and Data Classes|   [{{< fa display >}}](https://termehs.github.io/tidy08-data-types-classes)  |  [{{< fa file >}}](material/type-coercion.qmd)   [{{< fa file >}}](material/hotels-forcats.qmd)   [{{< fa file >}}](material/data-type-class-exercises.qmd) |  [.zip](material/data-types-classes.zip)|  [.qmd](material/hotels-forcats-ws.zip)|  
| **9**:  Importing and Recoding Data|   [{{< fa display >}}](https://termehs.github.io/tidy09-data-import-recode)  |  [{{< fa file >}}](material/nobels-csv.qmd)   [{{< fa file >}}](material/sales-excel.qmd)   [{{< fa file >}}](material/nyc-flights.qmd) |  [.zip](material/data-import-recode.zip)| [.qmd](material/nyc-flights-ws.zip)  |  |  [.qmd](material/nyc-flights-ws.zip)|  
| **10**: Functions and Iteration |  [{{< fa display >}}](https://termehs.github.io/tidy10-functions-iteration)  |  [{{< fa file >}}](material/uoe-art.qmd)    |  |  |