---
title: Data Science with Tidyverse II
subtitle: Tidymodeling
description: |
  The tidymodels framework is a collection of packages for modeling using tidyverse principles. This course introduces the principles and practices of predictive modeling using this framework in R. Designed for learners with R knowledge, the course emphasizes building, evaluating, and deploying machine learning models in a tidy and reproducible manner. Students will gain hands-on experience with data preprocessing, feature engineering, model tuning, and evaluation, using real-world datasets. The course consists of two parts, one introductory and one more advanced. These parts are combianed with several case studies for more practice.
section-divs: false
toc: false
margin-footer: The teaching material here is inspired and adapted from <https://tidymodels.org> and <https://workshops.tidymodels.org> and licenced under Creative Commons Attribution [CC BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/).
---


:::{.highlight}
*Make sure to install and load Tidymodels:*
```{r}
#| eval: false
install.packages("tidymodels")
library(tidymodels)
```
:::


## Course Material
<br>

|                                                    | Slides  | Worksheet
|----------------------------------------------------|:------:|:---------
| **Introduction** | [{{< fa display >}}](https://termehs.github.io/tidy-II-intro) | 
| **Part I** |   [{{< fa display >}}](https://termehs.github.io/tidy-II-part1)  | 1.Your Data Budget  [{{< fa file >}}](material/1-data-budget.zip) 
| |    | 2. Build a Model [{{< fa file >}}](material/2-what-makes-a-model.zip)
| |    | 3. Evaluate the Model [{{< fa file >}}](material/3-evaluate-model.zip)   
| |    | 4. Model Tuning [{{< fa file >}}](material/4-tuning-models.zip)
| **Part II** |    [{{< fa display >}}](https://termehs.github.io/tidy-II-part2) | 1. Feature Engineering [{{< fa file >}}](material/1-feature-engineering.zip)  |
| |    | 2. Tuning Hyperparameters [{{< fa file >}}](material/2-tuning-hyperparameters.zip)
| |    | 3. Grid Search via Racing [{{< fa file >}}](material/3-grid-search-via-racing.zip)
| |    | 4. Iterative Search [{{< fa file >}}](material/4-iterative-search.zip) 
| **Case Study** |   to be added |
<br>


###   Extensions & Hands-On Exercises 
|                                          | Practical  | Worksheet 
|----------------------------------------------------|:------:|:---------
**K-means** |  [{{< fa file >}}](material/case-studies/k-means.qmd)  | [{{< fa file >}}](material/case-studies/k-means-ws.zip) |
**Bootstrapping** |  [{{< fa file >}}](material/case-studies/bootstrap.qmd)  |  [{{< fa file >}}](material/case-studies/bootstrap-ws.zip)   |

<br><br>


<br><br>




