---
title: Social Network Analysis
subtitle: MSc course 
description: |
  This course is an introduction to the statistical analysis and modeling of social networks. The course aims to give a basic understanding of and a working handle on drawing inference for network structure and actor level attributes for both cross-sectional and longitudinal network data. A fundamental notion of the course will be on how the structure of observed graphs relate to various forms of random graphs. This will be developed in the context of non-parametric approaches, and elaborated to the analysis of networks using models such as Exponential Random Graph Models (ERGMs) and Stochastic Actor Oriented Models (SAOMs). The students will be provided several hands-on exercises and will apply the covered approaches to a suite of real world data sets. 
section-divs: false
toc: false
---
 
The course text book can be found here: [R4SNA](https://schochastics.github.io/R4SNA/) (work in progress)



## Schedule

|                                                    | slides  | practical | data | worksheet | 
|----------------------------------------------------|:------:|:---------:|:---------:|:---------:|
| **1**: Introduction | [{{< fa display >}}](https://termehs.github.io/sna01-intro)  |  [{{< fa file >}}](material/01/01-intro-pkgs.qmd)    |  |  [.qmd](material/01/01-intro-pkgs-ws.zip)  |
| **2**: The Language of Networks| [{{< fa display >}}](https://termehs.github.io/sna02-graph-theory)  |  [{{< fa file >}}](material/02/02-graph-theory.qmd)    |  |  [.qmd](material/02/02-graph-theory-ws.zip)  |
| **3**:  Network Concepts and Descriptives I | [{{< fa display >}}](https://termehs.github.io/sna03-descriptives-I)  |  [{{< fa file >}}](material/03/03-descriptives-1.qmd)    |  [.zip](material/03/data.zip)  |  [.qmd](material/03/03-descriptives-1-ws.zip)  | 
| **4**:  Network Concepts and Descriptives II | [{{< fa display >}}](https://termehs.github.io/sna04-descriptives-II)  |  [{{< fa file >}}](material/04/04-descriptives-2-bm.qmd)    [{{< fa file >}}](material/04/04-descriptives-2.qmd)  |  |  [.qmd](material/04/04-descriptives-II-ws.zip)  | 
| **5**:  Beyond 'Standard' Networks | [{{< fa display >}}](https://termehs.github.io/sna05-beyond-standard-nets)  |  [{{< fa file >}}](material/05/05-ego-nets.qmd)    [{{< fa file >}}](material/05/05-special-nets.qmd)  |  [.zip](material/05/data.zip)  |  [.qmd](material/05/beyond-standard-nets-ws.zip)  | 
| **6**:  Network Visualization I | [{{< fa display >}}](https://termehs.github.io/sna06-netviz-I)  |   [{{< fa file >}}](material/06/06-netviz-1.qmd)  |  |  [.qmd](material/06/06-netviz-1-ws.zip)  | 
| **7**:  Network Visualization II | [{{< fa display >}}](https://termehs.github.io/sna07-netviz-II)  |   [{{< fa file >}}](material/07/07-netviz-2.qmd)  |  |  [.qmd](material/07/07-netviz-2-ws.zip)  |
| **8**:  Network Modelling: Introduction| [{{< fa display >}}](material/08/08-intro_netmod.pdf)  |  [{{< fa file >}}](material/08/08-cugd.qmd)  |    |  [.qmd](material/08/08-cugd.zip)  | 
| **9**:  Random Graph Models| [{{< fa display >}}](material/09/09-rgm.pdf)  |  [{{< fa file >}}](material/09/09-rgm.qmd)  |    |  [.qmd](material/09/09-rgm.zip)  | 
| **10**: Exponential Random Graph Models (ERGMs)| [{{< fa display >}}](material/10/10-ergms.pdf)  |  [{{< fa file >}}](material/10/10-ergms1.qmd)  [{{< fa file >}}](material/10/10-ergms2.qmd)   |  [.zip](material/10/data.zip)    |  [.qmd](material/10/10-ergms1.zip)  [.qmd](material/10/10-ergms2-ws.zip)  | 
| **11**: Stochastic Actor Oriented Models (SAOMs)| [{{< fa display >}}](material/11/11-saoms.pdf)  |  [{{< fa file >}}](material/11/saoms-1.zip)  [{{< fa file >}}](material/11/saoms-2.zip)   |  [.zip](material/11/data.zip)  [.zip](material/11/data2.zip)      |   [.qmd](material/11/saoms-1.zip)   [.qmd](material/11/saoms-2.zip) | 
<br>


<br>


<br>

<br>


## R Packages

Throughout the course we will use a variety of different packages of doing network analysis, modeling and visualization. Make sure to install them all and have them ready to load when needed:

```{r install_packages}
#| eval: FALSE
install.packages("igraph")   
install.packages("statnet")  #installs ergm, network, and sna
install.packages("snahelper")
install.packages("netUtils")
install.packages("ggraph")
install.packages("backbone")
install.packages("netrankr")
install.packages("signnet")
install.packages("egor")
install.packages("intergraph")
install.packages("graphlayouts")
install.packages("visNetwork")
install.packages("patchwork")
install.packages("edgebundle")
install.packages("ggplot2")
install.packages("gganimate")
install.packages("ggforce")
install.packages("rsiena")

install.packages("remotes")
remotes::install_github("schochastics/networkdata")
```
